spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    #    host: localhost
    #    host: sqlvhnegrisoli.ddns.net
    #    port: 5672
    #    username: biotadmin
    #    password: biotadmin
    host: skunk.rmq.cloudamqp.com
    username: yfsypxcf
    password: wrX6LNWtKlsRd0l1ICC5TNEWf0yCpF1f
    virtual-host: yfsypxcf

  datasource:
    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:postgresql://ec2-54-235-246-201.compute-1.amazonaws.com:5432/d92mg9h3sucp78
#    username: mvhrsysowbxmxt
#    password: 9a95933171eaf333afbbc9f7d2705dffab7c87c650d01a2888c16496df721a2a
    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/nutricao_esportiva
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

oauth-clients:
  projeto_mvp_app:
    client: projeto_mvp_app-client
    secret: projeto_mvp_app-secret

server:
  port: 8091

app-config:
  queue:
    usuario-log: usuario-log.queue
  topic:
    biot-admin: biot-admin.topic
  key:
    usuario-log: usuario-log.queue

management:
  health:
    rabbit:
      enabled: false