spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
#    host: localhost
    host: sqlvhnegrisoli.ddns.net
    port: 5672
    username: biotadmin
    password: biotadmin

  datasource:
    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/nutricao_esportiva
    jdbc-url: jdbc:postgresql://localhost:5432/nutricao_esportiva
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

  redis:
#    host: sqlvhnegrisoli.ddns.net
    host: localhost
    port: 6379
    pool:
      max-active: 120
      max-idle: 40

oauth-clients:
  projeto_mvp_app:
    client: projeto_mvp_app-client
    secret: projeto_mvp_app-secret

server:
  port: 8091

app-config:
  queue:
    usuario-log: usuario-log.queue
  topic:
    biot-admin: biot-admin.topic
  key:
    usuario-log: usuario-log.queue
  enable-rabbit: true

management:
  health:
    rabbit:
      enabled: false